import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { Card, PageHeader, button, input } from "@/components/workspace-ui";
import { db } from "@/server/db";
import { classEnrollments, classes, students } from "@/server/schema";
import { requireWorkspace } from "@/server/session";
import { recordGroupLesson } from "./actions";
export default async function GroupRecord({params}:{params:Promise<{id:string}>}){const ctx=await requireWorkspace();const{id}=await params;const target=await db.select().from(classes).where(and(eq(classes.id,id),eq(classes.academyId,ctx.academy.id))).then(r=>r[0]);if(!target)notFound();const enrolled=await db.select({student:students}).from(classEnrollments).innerJoin(students,and(eq(students.id,classEnrollments.studentId),eq(students.academyId,ctx.academy.id))).where(and(eq(classEnrollments.classId,id),eq(classEnrollments.active,true)));return <><PageHeader eyebrow="Group attendance" title={target.name} description="Each enrolled student receives an individual attendance record and communication drafts."/><Card><form action={recordGroupLesson} className="space-y-5"><input type="hidden" name="classId" value={id}/><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Date<input name="lessonDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className={input}/></label><label className="text-sm font-bold">Shared topic/reference<input name="lessonReference" className={input}/></label></div>{enrolled.map(({student})=><fieldset key={student.id} className="rounded-xl border p-4"><legend className="px-2 font-bold">{student.displayName}</legend><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Attendance<select name={`attendance:${student.id}`} className={input}>{['Attended','Late','Absent','Excused'].map(x=><option key={x}>{x}</option>)}</select></label><Field name={`strength:${student.id}`} label="Individual progress"/><Field name={`practice:${student.id}`} label="Needs practice"/><Field name={`homework:${student.id}`} label="Homework"/></div></fieldset>)}<div className="grid gap-3 sm:grid-cols-2"><button name="intent" value="draft" className="min-h-12 rounded-xl border font-bold">Save group draft</button><button name="intent" value="complete" className={button}>Complete individual reports</button></div></form></Card></>}
function Field({name,label}:{name:string;label:string}){return <label className="text-sm font-bold">{label}<textarea name={name} className={`${input} min-h-20 py-3`}/></label>}
