import Link from "next/link";
import { desc, eq } from "drizzle-orm";
import { Card, Empty, PageHeader, button, input } from "@/components/workspace-ui";
import { db } from "@/server/db";
import { lessons, memberships, students } from "@/server/schema";
import { requireWorkspace } from "@/server/session";

export default async function Reports(){const ctx=await requireWorkspace();const list=db.select().from(lessons).where(eq(lessons.academyId,ctx.academy.id)).orderBy(desc(lessons.lessonDate)).all();const studentList=db.select().from(students).where(eq(students.academyId,ctx.academy.id)).all();const teachers=db.select().from(memberships).where(eq(memberships.academyId,ctx.academy.id)).all();return <><PageHeader eyebrow="Academy records" title="Reports and progress history" description="Every filter and export is enforced against the active academy on the server." action={<Link href="/api/exports/lessons" className={button}>Download CSV</Link>}/><Card><form method="get" action="/api/exports/lessons" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select name="student" label="Student" options={studentList.map(s=>[s.id,s.displayName])}/><Select name="teacher" label="Teacher membership" options={teachers.map(t=>[t.id,`${t.role} · ${t.id.slice(0,8)}`])}/><label className="text-xs font-bold">Track<input name="track" className={input}/></label><Select name="attendance" label="Attendance" options={['Attended','Late','Absent','Excused'].map(x=>[x,x])}/><label className="text-xs font-bold">From<input name="from" type="date" className={input}/></label><label className="text-xs font-bold">To<input name="to" type="date" className={input}/></label><button className={`${button} self-end`}>Export filtered CSV</button></form>{list.length?<div className="mt-6 divide-y">{list.map(l=><div key={l.id} className="py-3"><strong>{l.lessonDate} · {l.status.replaceAll('_',' ')}</strong><p className="text-sm text-slate-500">{l.learningTrack} · {l.lessonReference||'No progress recorded'}</p></div>)}</div>:<Empty>No report history yet. Missing reports will appear on the dashboard once classes have enrolled students.</Empty>}</Card></>}
function Select({name,label,options}:{name:string;label:string;options:string[][]}){return <label className="text-xs font-bold">{label}<select name={name} className={input}><option value="">All</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
