"use server";
import { and, eq } from "drizzle-orm";
import { redirect } from "next/navigation";
import { approvePayment } from "@/lib/saas";
import { db } from "@/server/db";
import { academySubscriptions, auditEvents, memberships, notifications, paymentRequests, platformSettings, user } from "@/server/schema";
import { sendTransactionalEmail } from "@/server/email";
import { isPlatformAdmin, requireUser } from "@/server/session";
async function admin(){const session=await requireUser();if(!isPlatformAdmin(session.user.email))throw new Error("Platform administrator access required.");return session}
export async function reviewPayment(form:FormData){const session=await admin();const id=String(form.get("id"));const decision=String(form.get("decision"));const reason=String(form.get("reason")??"").trim();if(decision!=="approve"&&!reason)throw new Error("A rejection reason is required.");const request=await db.select().from(paymentRequests).where(eq(paymentRequests.id,id)).then(rows=>rows[0]);if(!request||request.status!=="pending")throw new Error("Pending request not found.");const stamp=new Date().toISOString();const owners=await db.select({userId:memberships.userId,email:user.email}).from(memberships).innerJoin(user,eq(user.id,memberships.userId)).where(and(eq(memberships.academyId,request.academyId),eq(memberships.role,"owner"),eq(memberships.active,true)));await db.transaction(async(tx)=>{if(decision==="approve"){const approved=approvePayment(request,session.user.id);await tx.update(paymentRequests).set({...approved,updatedAt:stamp}).where(and(eq(paymentRequests.id,id),eq(paymentRequests.status,"pending")));await tx.update(academySubscriptions).set({status:"active",periodStartsAt:stamp,periodEndsAt:new Date(Date.now()+30*86400000).toISOString(),updatedAt:stamp}).where(eq(academySubscriptions.academyId,request.academyId));}else await tx.update(paymentRequests).set({status:"rejected",reviewedBy:session.user.id,reviewedAt:stamp,rejectionReason:reason,updatedAt:stamp}).where(and(eq(paymentRequests.id,id),eq(paymentRequests.status,"pending")));for(const owner of owners)await tx.insert(notifications).values({id:crypto.randomUUID(),academyId:request.academyId,userId:owner.userId,title:decision==="approve"?"Payment approved":"Payment rejected",body:decision==="approve"?`Payment ${request.reference} was approved.`:`Payment ${request.reference} was rejected: ${reason}`,createdAt:stamp});await tx.insert(auditEvents).values({id:crypto.randomUUID(),academyId:request.academyId,actorUserId:session.user.id,action:`payment.${decision==="approve"?"approved":"rejected"}`,entityType:"payment_request",entityId:id,metadata:{reason:reason||null},occurredAt:stamp});});for(const owner of owners)await sendTransactionalEmail({kind:decision==="approve"?"payment_approved":"payment_rejected",to:owner.email,subject:decision==="approve"?"DarsFlow payment approved":"DarsFlow payment rejected",text:decision==="approve"?`Your payment ${request.reference} was approved.`:`Your payment ${request.reference} was rejected: ${reason}`,idempotencyKey:`payment-decision:${id}:${decision}:${owner.userId}`});redirect("/platform")}
export async function savePaymentInstructions(form:FormData){const session=await admin();const stamp=new Date().toISOString();await db.update(platformSettings).set({paymentInstructions:String(form.get("instructions")??"").trim()||null,updatedBy:session.user.id,updatedAt:stamp}).where(eq(platformSettings.id,"default"));redirect("/platform")}
