"use server";
import { and, eq } from "drizzle-orm";
import { redirect } from "next/navigation";
import { approvePayment } from "@/lib/saas";
import { db } from "@/server/db";
import { academies, academySubscriptions, auditEvents, memberships, notifications, paymentRequests, platformSettings, subscriptionPlans, user } from "@/server/schema";
import { sendTransactionalEmail } from "@/server/email";
import { isPlatformAdmin, requireUser } from "@/server/session";
async function admin(){const session=await requireUser();if(!isPlatformAdmin(session.user.email))throw new Error("Platform administrator access required.");return session}
export async function reviewPayment(form:FormData){const session=await admin();const id=String(form.get("id"));const decision=String(form.get("decision"));const reason=String(form.get("reason")??"").trim();if(decision!=="approve"&&!reason)throw new Error("A rejection reason is required.");const request=await db.select().from(paymentRequests).where(eq(paymentRequests.id,id)).then(rows=>rows[0]);if(!request||request.status!=="pending")throw new Error("Pending request not found.");const stamp=new Date().toISOString();const owners=await db.select({userId:memberships.userId,email:user.email}).from(memberships).innerJoin(user,eq(user.id,memberships.userId)).where(and(eq(memberships.academyId,request.academyId),eq(memberships.role,"owner"),eq(memberships.active,true)));await db.transaction(async(tx)=>{if(decision==="approve"){const approved=approvePayment(request,session.user.id);await tx.update(paymentRequests).set({...approved,updatedAt:stamp}).where(and(eq(paymentRequests.id,id),eq(paymentRequests.status,"pending")));await tx.update(academySubscriptions).set({status:"active",periodStartsAt:stamp,periodEndsAt:new Date(Date.now()+30*86400000).toISOString(),updatedAt:stamp}).where(eq(academySubscriptions.academyId,request.academyId));}else await tx.update(paymentRequests).set({status:"rejected",reviewedBy:session.user.id,reviewedAt:stamp,rejectionReason:reason,updatedAt:stamp}).where(and(eq(paymentRequests.id,id),eq(paymentRequests.status,"pending")));for(const owner of owners)await tx.insert(notifications).values({id:crypto.randomUUID(),academyId:request.academyId,userId:owner.userId,dedupeKey:`payment-${decision}:${id}:${owner.userId}`,title:decision==="approve"?"Payment approved":"Payment rejected",body:decision==="approve"?`Payment ${request.reference} was approved.`:`Payment ${request.reference} was rejected: ${reason}`,createdAt:stamp}).onConflictDoNothing();await tx.insert(auditEvents).values({id:crypto.randomUUID(),academyId:request.academyId,actorUserId:session.user.id,action:`payment.${decision==="approve"?"approved":"rejected"}`,entityType:"payment_request",entityId:id,metadata:{reason:reason||null},occurredAt:stamp});});for(const owner of owners)await sendTransactionalEmail({kind:decision==="approve"?"payment_approved":"payment_rejected",to:owner.email,subject:decision==="approve"?"DarsFlow payment approved":"DarsFlow payment rejected",text:decision==="approve"?`Your payment ${request.reference} was approved.`:`Your payment ${request.reference} was rejected: ${reason}`,idempotencyKey:`payment-decision:${id}:${decision}:${owner.userId}`});redirect("/platform")}
export async function savePaymentInstructions(form:FormData){const session=await admin();const stamp=new Date().toISOString();await db.update(platformSettings).set({paymentInstructions:String(form.get("instructions")??"").trim()||null,updatedBy:session.user.id,updatedAt:stamp}).where(eq(platformSettings.id,"default"));redirect("/platform")}
export async function savePlan(form:FormData){await admin();const id=String(form.get("id")||crypto.randomUUID());const stamp=new Date().toISOString();const values={name:String(form.get("name")??"").trim(),description:String(form.get("description")??"").trim()||null,priceMinor:Math.round(Number(form.get("price")||0)*100),currency:String(form.get("currency")||"PKR"),activeStudentLimit:Number(form.get("studentLimit")),activeTeacherLimit:Number(form.get("teacherLimit")),trialDays:Number(form.get("trialDays")||14),graceDays:Number(form.get("graceDays")||7),active:form.get("active")==="true",updatedAt:stamp};if(!values.name||!Number.isInteger(values.activeStudentLimit)||!Number.isInteger(values.activeTeacherLimit))throw new Error("Valid plan details are required.");await db.insert(subscriptionPlans).values({id,...values,createdAt:stamp}).onConflictDoUpdate({target:subscriptionPlans.id,set:values});redirect("/platform")}
export async function changeAcademySubscription(form:FormData){const session=await admin();const academyId=String(form.get("academyId"));const action=String(form.get("subscriptionAction"));const reason=String(form.get("reason")??"").trim();if(!reason)throw new Error("A reason is required.");const academy=await db.select().from(academies).where(eq(academies.id,academyId)).then(r=>r[0]);if(!academy)throw new Error("Academy not found.");const stamp=new Date().toISOString();const updates=action==="suspend"?{status:"suspended"}:action==="reactivate"?{status:"active"}:action==="extend_trial"?{status:"trialing",trialEndsAt:new Date(Date.now()+Number(form.get("days")||7)*86400000).toISOString()}:{status:"grace_period",periodEndsAt:new Date(Date.now()+Number(form.get("days")||7)*86400000).toISOString()};await db.transaction(async tx=>{await tx.update(academySubscriptions).set({...updates,updatedAt:stamp}).where(eq(academySubscriptions.academyId,academyId));await tx.update(academies).set({status:updates.status,updatedAt:stamp}).where(eq(academies.id,academyId));await tx.insert(auditEvents).values({id:crypto.randomUUID(),academyId,actorUserId:session.user.id,action:`subscription.${action}`,entityType:"academy_subscription",entityId:academyId,metadata:{reason},occurredAt:stamp});});redirect("/platform")}
